// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as dashboard$0 from "../../../../ao-data/albiondata-client/internal/dashboard/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "counters:snapshot": { [_ in string]?: number };
            "log:line": dashboard$0.LogLine;
            "status:changed": dashboard$0.Status;
        }
    }
}
