//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dashboard$0 from "../../../../ao-data/albiondata-client/internal/dashboard/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "counters:snapshot": $$createType0,
        "log:line": $$createType1,
        "status:changed": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = dashboard$0.LogLine.createFrom;
const $$createType2 = dashboard$0.Status.createFrom;

configure();
