# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: MacOS Builder

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -ldflags "-s -w -X main.version=$GITHUB_REF_NAME" albiondata-client.go

    - name: ls
      run: ls -la

    - name: gzip
      run: gzip -k9 albiondata-client

    - name: mv
      run: mv albiondata-client.gz update-darwin-amd64.gz
      
    - name: package
      run: |
        TEMP="albiondata-client"
        ZIPNAME="albiondata-client-amd64-mac.zip"
        rm -rfv ./scripts/$TEMP
        rm -rfv ./$ZIPNAME
        rm -rfv ./scripts/update-darwin-amd64.zip
        mkdir -v ./scripts/$TEMP
        cp -v albiondata-client ./scripts/$TEMP/albiondata-client-executable
        cd scripts
        cp -v run.command ./$TEMP/run.command
        # chown -Rv ${USER}:${USER} ./$TEMP
        chmod -v 777 ./$TEMP/*
        zip -v ../$ZIPNAME -r ./"$TEMP"      
      
    - name: ls
      run: ls -la
      
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: update-darwin-amd64.gz
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: albiondata-client-amd64-mac.zip
      
