# .github/workflows/test-build.yaml

on: 
  push:
  pull_request:

jobs:
  build-linux:
    name: Build Linux Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
    - name: Build
      run: make build-linux

    - uses: actions/upload-artifact@v4
      if: ${{ env.ACT }}
      with:
        name: files
        path: albiondata-client

    - uses: actions/upload-artifact@v4
      if: ${{ env.ACT }}
      with:
        name: files
        path: update-linux-amd64.gz

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper build-essential

    - name: Prepare package directory
      run: |
        mkdir -p pkg/deb/usr/bin
        cp albiondata-client pkg/deb/usr/bin

    - name: Create changelog
      run: |
        cd pkg/deb/
        VERSION=$(echo "$GITHUB_REF_NAME" | sed 's/[^0-9.]*//g')  # Keep only digits and dots
        DEBEMAIL="dhjen@outlook.com" dch --create --newversion $VERSION --package albiondata-client "$GITHUB_REF_NAME test build"

    - name: Build Debian package
      run: |
        cd pkg/deb
        debuild -b -us -uc

    - uses: actions/upload-artifact@v4
      if: ${{ env.ACT }}
      with:
        name: files
        path: pkg/*.deb

  build-windows:
    name: Build Windows Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: install nsis
      run: sudo apt-get update; sudo apt-get -y install nsis

    - name: Make
      run: make build-windows

    - uses: actions/upload-artifact@v4
      if: ${{ env.ACT }}
      with:
        name: files
        path: albiondata-client.exe

    - uses: actions/upload-artifact@v4
      if: ${{ env.ACT }}
      with:
        name: files
        path: update-windows-amd64.exe.gz

    - uses: actions/upload-artifact@v4
      if: ${{ env.ACT }}
      with:
        name: files
        path: albiondata-client-amd64-installer.exe

  build-darwin:
    name: Build MacOS Client
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -ldflags "-s -w -X main.version=$GITHUB_REF_NAME" albiondata-client.go

    - name: ls
      run: ls -la

    - name: gzip
      run: gzip -k9 albiondata-client

    - name: mv
      run: mv albiondata-client.gz update-darwin-amd64.gz

    - name: package
      run: |
        TEMP="albiondata-client"
        ZIPNAME="albiondata-client-amd64-mac.zip"
        rm -rfv ./scripts/$TEMP
        rm -rfv ./$ZIPNAME
        rm -rfv ./scripts/update-darwin-amd64.zip
        mkdir -v ./scripts/$TEMP
        cp -v albiondata-client ./scripts/$TEMP/albiondata-client-executable
        cd scripts
        cp -v run.command ./$TEMP/run.command
        # chown -Rv ${USER}:${USER} ./$TEMP
        chmod -v 777 ./$TEMP/*
        zip -v ../$ZIPNAME -r ./"$TEMP"

    - name: ls
      run: ls -la
